"""The KPI semantic contract: one authoritative definition per KPI, shown
on the KPI Contract page and referenced elsewhere so the whole app agrees
on what each number actually means.
"""

KPI_CONTRACT = {
    "Revenue": {
        "definition": "Total realized sales value across all products and stores in scope.",
        "formula": "SUM(transaction_amount)",
        "unit": "INR",
        "source": "Sales Transactions",
        "grain": "Store / day",
        "refresh_cadence": "Daily",
        "historical_coverage": "120 days",
        "baseline_method": "Mean of the prior 3 comparable 30-day periods",
        "materiality_threshold": "INR 1,000,000 absolute movement AND p < 0.05",
        "drivers": ["Transaction Volume", "Pricing / Product Mix", "Promotions", "Staffing / Wait Time"],
        "owner": "Finance",
        "lineage": "POS -> daily batch ETL -> transactions table -> KPI engine",
        "access_restriction": "None",
    },
    "Transactions": {
        "definition": "Count of completed sales transactions.",
        "formula": "COUNT(transaction_id)",
        "unit": "count",
        "source": "Sales Transactions",
        "grain": "Store / day",
        "refresh_cadence": "Daily",
        "historical_coverage": "120 days",
        "baseline_method": "Mean of the prior 3 comparable 30-day periods",
        "materiality_threshold": "Statistical significance (p < 0.05) on daily counts",
        "drivers": ["Footfall", "Wait Time", "Promotions", "Staffing"],
        "owner": "Store Operations",
        "lineage": "POS -> daily batch ETL -> transactions table -> KPI engine",
        "access_restriction": "None",
    },
    "Average Ticket": {
        "definition": "Average realized revenue per transaction.",
        "formula": "Revenue / Transactions",
        "unit": "INR",
        "source": "Sales Transactions (derived)",
        "grain": "Store / day",
        "refresh_cadence": "Daily",
        "historical_coverage": "120 days",
        "baseline_method": "Derived from Revenue and Transactions baselines",
        "materiality_threshold": "2% relative movement",
        "drivers": ["Pricing", "Product Mix", "Promotions"],
        "owner": "Finance",
        "lineage": "Derived metric, computed in the KPI engine",
        "access_restriction": "None",
    },
    "Wait Time": {
        "definition": "Average customer wait time at point of sale.",
        "formula": "MEAN(wait_time)",
        "unit": "minutes",
        "source": "Operations / Staffing",
        "grain": "Store / hour / day",
        "refresh_cadence": "Hourly",
        "historical_coverage": "120 days",
        "baseline_method": "Mean of the prior 3 comparable 30-day periods",
        "materiality_threshold": "Statistical significance (p < 0.05) on daily averages",
        "drivers": ["Staffing Availability", "Demand Volume"],
        "owner": "Store Operations",
        "lineage": "Workforce scheduling system -> hourly sync -> staffing table -> KPI engine",
        "access_restriction": "None",
    },
}
