import os
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import streamlit as st

from app.config.settings import APP_SUBTITLE, APP_TITLE, PERSONAS
from app.data.loader import get_datasets
from app.entitlement.entitlement import allowed_locations, enforce_default_location
from app.views import (
    action_simulator_page, counterfactuals_page, data_sources_page, driver_analysis_page,
    evidence_explorer, executive_overview, feedback_page, kpi_contract_page, kpi_explorer, telemetry_page,
)

st.set_page_config(
    page_title=f"{APP_TITLE} — Executive Intelligence",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom High-Contrast, Dark-Sidebar Executive Styling System
with open("app/style.css") as f:
    st.markdown(f"<style>\n{f.read()}\n</style>", unsafe_allow_html=True)


PAGES = {
    "Workspace": {
        "Executive Overview": executive_overview,
        "KPI Explorer": kpi_explorer,
        "Driver Analysis": driver_analysis_page,
        "Counterfactuals": counterfactuals_page,
        "Action Simulator": action_simulator_page,
    },
    "Data": {
        "Data Sources": data_sources_page,
        "KPI Contract": kpi_contract_page,
    },
    "System": {
        "Feedback": feedback_page,
        "Telemetry": telemetry_page,
    },
}

with st.sidebar:
    st.markdown(
        textwrap.dedent("""
<div class="sidebar-brand">BusinessIntelligence<span>.ai</span></div>
<div class="sidebar-tagline">Causal KPI-to-Action Engine</div>
""").strip(),
        unsafe_allow_html=True,
    )

    if "active_page" not in st.session_state:
        st.session_state.active_page = "Executive Overview"

    for group_name, pages in PAGES.items():
        st.markdown(f'<div class="sidebar-group-title">{group_name}</div>', unsafe_allow_html=True)
        for page_name in pages:
            is_active = st.session_state.active_page == page_name
            if st.button(
                page_name,
                key=f"nav_{page_name}",
                use_container_width=True,
                type="primary" if is_active else "secondary",
            ):
                st.session_state.active_page = page_name

if "persona" not in st.session_state:
    st.session_state.persona = "CEO / Executive"
if "_prev_persona" not in st.session_state:
    st.session_state._prev_persona = st.session_state.persona

# Topbar with title, subtitle, and selectors
top_left, top_r1, top_r2 = st.columns([2.5, 1.2, 1.2])
with top_left:
    top_html = textwrap.dedent(f"""
<div class="topbar-title">Business Performance Overview</div>
<div class="topbar-subtitle">{APP_SUBTITLE}</div>
""").strip()
    st.markdown(top_html, unsafe_allow_html=True)

with top_r1:
    persona = st.selectbox("Active Persona", PERSONAS, key="persona")

# We don't need the manual session state reset for location anymore if we scope the key to the persona.
# But we'll keep the _prev_persona check just in case we need to trigger a hard rerun on persona change.
if persona != st.session_state._prev_persona:
    st.session_state._prev_persona = persona
    st.rerun()

with top_r2:
    location_options = allowed_locations(persona)
    
    # Scope the session state key to the persona so switching personas creates a fresh selectbox
    loc_key = f"location_{persona}"
    
    default_location = enforce_default_location(persona, st.session_state.get(loc_key, location_options[0]))
    location_label = st.selectbox(
        "Location / Branch",
        location_options,
        index=location_options.index(default_location),
        key=loc_key,
    )

st.markdown("<div style='height: 12px;'></div>", unsafe_allow_html=True)

datasets = get_datasets()
active_group = next(g for g in PAGES if st.session_state.active_page in PAGES[g])
active_module = PAGES[active_group][st.session_state.active_page]

active_module.render(datasets, persona, location_label)

st.divider()
footer_html = textwrap.dedent("""
<div style="color: #475569; font-size: 12px; font-weight: 500; line-height: 1.5; margin-top: 10px;">
<b>Prototype UI • Synthetic CaféCo data</b><br>
Numeric attribution is generated by deterministic statistical logic; RAG provides contextual evidence;
LLMs are limited to evidence extraction and narrative generation.
</div>
""").strip()
st.markdown(footer_html, unsafe_allow_html=True)
